# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [1]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [3]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [4]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [5]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population shortname    state info.governor
0        Dade       12345        FL  Florida    Rick Scott
1     Broward       40000        FL  Florida    Rick Scott
2  Palm Beach       60000        FL  Florida    Rick Scott
3      Summit        1234        OH     Ohio   John Kasich
4    Cuyahoga        1337        OH     Ohio   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [6]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'code': 'EX', 'name': 'Education'},
   {'code': 'EX', 'name': 'Education'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'},
   {'code': 'EX', 'name': 'Education'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'code': '8', 'name': 'Human development'},
   {'code': '11', 'name': ''}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocDate': '28-AUG-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'EntityID': '090224b081e545fb_1_0'},
   {'DocDate': '01-JUL-2013',
    'DocType': 'IP',
    'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'EntityID': '000442464_20130920111729'},
   {'DocDate': '22-NOV-2012',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'EntityID': '090224b0817b19e2_1_0'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'code': 'EP', 'name': 'Primary education'},
   {'code': 'ES', 'name': 'Secondary education'},
   {'code': 'BS', 'name': 'Public administration- Other social services'},
   {'code': 'ET', 'name': 'Tertiary education'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'code': '65', 'name': 'Education for all'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'code': 'BX',
    'name': 'Public Administration, Law, and Justice'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'code': '1', 'name': 'Economic management'},
   {'code': '6', 'name': 'Social protection and risk management'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'EntityID': '000333037_20131024115616'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'EntityID': '000356161_20131024151611'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'EntityID': '000442464_20131031112136'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'EntityID': '000333037_20131031105716'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'EntityID': '000356161_20130305113209'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'EntityID': '000356161_20130305113716'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'code': 'BS',
    'name': 'Public administration- Other social services'},
   {'code': 'BZ', 'name': 'General public administration sector'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'code': '24', 'name': 'Other economic management'},
   {'code': '54', 'name': 'Social safety nets'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

In [7]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [251]:
# load json data as Pandas dataframe

df_json = pd.read_json(open('data/world_bank_projects.json'))
df_json.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [252]:
# display dataframe columns names and types

df_json.dtypes

_id                         object
approvalfy                   int64
board_approval_month        object
boardapprovaldate           object
borrower                    object
closingdate                 object
country_namecode            object
countrycode                 object
countryname                 object
countryshortname            object
docty                       object
envassesmentcategorycode    object
grantamt                     int64
ibrdcommamt                  int64
id                          object
idacommamt                   int64
impagency                   object
lendinginstr                object
lendinginstrtype            object
lendprojectcost              int64
majorsector_percent         object
mjsector_namecode           object
mjtheme                     object
mjtheme_namecode            object
mjthemecode                 object
prodline                    object
prodlinetext                object
productlinetype             object
project_abstract            object
project_name                object
projectdocs                 object
projectfinancialtype        object
projectstatusdisplay        object
regionname                  object
sector                      object
sector1                     object
sector2                     object
sector3                     object
sector4                     object
sector_namecode             object
sectorcode                  object
source                      object
status                      object
supplementprojectflg        object
theme1                      object
theme_namecode              object
themecode                   object
totalamt                     int64
totalcommamt                 int64
url                         object
dtype: object

## 1. Find the 10 countries with most projects:

In [253]:
# load json file to a string object

jdata = json.load((open('data/world_bank_projects.json')))

In [301]:
# get normalized theme, country, and project data subset

df_theme = json_normalize(jdata, 'mjtheme_namecode', ['countryname', 'project_name', ['_id', '$oid' ]])
df_theme.head()

,code,name,_id.$oid,countryname,project_name
0,8,Human development,52b213b38594d8a2be17c780,Federal Democratic Republic of Ethiopia,Ethiopia General Education Quality Improvement...
1,11,,52b213b38594d8a2be17c780,Federal Democratic Republic of Ethiopia,Ethiopia General Education Quality Improvement...
2,1,Economic management,52b213b38594d8a2be17c781,Republic of Tunisia,TN: DTF Social Protection Reforms Support
3,6,Social protection and risk management,52b213b38594d8a2be17c781,Republic of Tunisia,TN: DTF Social Protection Reforms Support
4,5,Trade and integration,52b213b38594d8a2be17c782,Tuvalu,Tuvalu Aviation Investment Project - Additiona...

In [302]:
# rename the project id, theme code and theme name columns

df_theme=df_theme.rename(columns = {'_id.$oid':'project_id', 'code':'theme_code', 'name':'theme_name'})
df_theme.head()

,theme_code,theme_name,project_id,countryname,project_name
0,8,Human development,52b213b38594d8a2be17c780,Federal Democratic Republic of Ethiopia,Ethiopia General Education Quality Improvement...
1,11,,52b213b38594d8a2be17c780,Federal Democratic Republic of Ethiopia,Ethiopia General Education Quality Improvement...
2,1,Economic management,52b213b38594d8a2be17c781,Republic of Tunisia,TN: DTF Social Protection Reforms Support
3,6,Social protection and risk management,52b213b38594d8a2be17c781,Republic of Tunisia,TN: DTF Social Protection Reforms Support
4,5,Trade and integration,52b213b38594d8a2be17c782,Tuvalu,Tuvalu Aviation Investment Project - Additiona...

In [303]:
# get the list of unique projects and countries

df_proj = df_theme[['project_id', 'project_name', 'countryname',]]
df_proj.drop_duplicates(inplace = True)
df_proj.head()

D:\Anaconda3\lib\site-packages\pandas\util\decorators.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return func(*args, **kwargs)

,project_id,project_name,countryname
0,52b213b38594d8a2be17c780,Ethiopia General Education Quality Improvement...,Federal Democratic Republic of Ethiopia
2,52b213b38594d8a2be17c781,TN: DTF Social Protection Reforms Support,Republic of Tunisia
4,52b213b38594d8a2be17c782,Tuvalu Aviation Investment Project - Additiona...,Tuvalu
8,52b213b38594d8a2be17c783,Gov't and Civil Society Organization Partnership,Republic of Yemen
10,52b213b38594d8a2be17c784,Second Private Sector Competitiveness and Econ...,Kingdom of Lesotho

In [304]:
# get the top 10 countries with most projects

top10_cn_most_proj = df_proj.groupby(['countryname'])['project_name'] \
                            .count() \
                            .reset_index(name='count') \
                            .sort_values(['count'], ascending=False) \
                            .head(10) 

top10_cn_most_proj.reset_index(drop=True, inplace=True)
top10_cn_most_proj

                       countryname  count
0       People's Republic of China     19
1            Republic of Indonesia     19
2    Socialist Republic of Vietnam     17
3                Republic of India     16
4                Republic of Yemen     13
5  People's Republic of Bangladesh     12
6                            Nepal     12
7               Kingdom of Morocco     12
8           Republic of Mozambique     11
9                           Africa     11

## 2. Find the top 10 major project themes:

In [316]:
# get the top 10  project themes

top10_proj_theme = df_theme.groupby(['theme_name'])['theme_name'] \
                            .count() \
                            .reset_index(name='count') \
                            .sort_values(['count'], ascending=False) \
                            .head(10) 

top10_proj_theme.reset_index(drop=True, inplace=True)
top10_proj_theme

                                     theme_name  count
0  Environment and natural resources management    223
1                             Rural development    202
2                             Human development    197
3                      Public sector governance    184
4         Social protection and risk management    158
5      Financial and private sector development    130
6                                                  122
7                   Social dev/gender/inclusion    119
8                         Trade and integration     72
9                             Urban development     47

## 3. Create a dataframe with filled project theme names:

In [305]:
# get a dataframe with unique theme_code and theme_name (non-empty) to use as refrence table 

df_theme_ref = df_theme.loc[df_theme['theme_name'] != ''][['theme_code', 'theme_name']].drop_duplicates()
df_theme_ref

    theme_code                                    theme_name
0            8                             Human development
2            1                           Economic management
3            6         Social protection and risk management
4            5                         Trade and integration
5            2                      Public sector governance
6           11  Environment and natural resources management
8            7                   Social dev/gender/inclusion
11           4      Financial and private sector development
18          10                             Rural development
53           9                             Urban development
252          3                                   Rule of law

In [314]:
# merge the orignal data frame with the refrence data frame

df_theme_new = df_theme.merge(df_theme_ref, on='theme_code')
df_theme_new.head(20)

,theme_code,theme_name_x,project_id,countryname,project_name,theme_name_y
0,8,Human development,52b213b38594d8a2be17c780,Federal Democratic Republic of Ethiopia,Ethiopia General Education Quality Improvement...,Human development
1,8,,52b213b38594d8a2be17c787,People's Republic of China,China Renewable Energy Scale-Up Program Phase II,Human development
2,8,Human development,52b213b38594d8a2be17c791,Republic of Madagascar,Emergency Support to Education For all Project,Human development
3,8,Human development,52b213b38594d8a2be17c792,Kingdom of Cambodia,Additional Financing for the Second Health Sec...,Human development
4,8,Human development,52b213b38594d8a2be17c792,Kingdom of Cambodia,Additional Financing for the Second Health Sec...,Human development
5,8,Human development,52b213b38594d8a2be17c792,Kingdom of Cambodia,Additional Financing for the Second Health Sec...,Human development
6,8,Human development,52b213b38594d8a2be17c797,Republic of Tajikistan,Tajikistan JSDF Nutrition Grant Scale Up,Human development
7,8,Human development,52b213b38594d8a2be17c797,Republic of Tajikistan,Tajikistan JSDF Nutrition Grant Scale Up,Human development
8,8,Human development,52b213b38594d8a2be17c79a,Lao People's Democratic Republic,Lao PDR Ninth Poverty Reduction Support Operation,Human development
9,8,Human development,52b213b38594d8a2be17c79e,People's Republic of Angola,Angola Learning for All Project,Human development
10,8,Human development,52b213b38594d8a2be17c7a2,People's Republic of Bangladesh,Additional Financing: Skills and Training Enha...,Human development
11,8,Human development,52b213b38594d8a2be17c7a9,Republic of Congo,Congo Skills Development for Employability Pro...,Human development
12,8,,52b213b38594d8a2be17c7ab,Democratic Republic of Sao Tome and Prin,Sao Tome & Principe-Extractive Industries Tran...,Human development
13,8,Human development,52b213b38594d8a2be17c7ad,Africa,West Africa Regional Disease Surveillance Cap...,Human development
14,8,Human development,52b213b38594d8a2be17c7b6,Republic of Sierra Leone,SL-RCHP2 Add'l Financing (FY13),Human development
15,8,Human development,52b213b38594d8a2be17c7b6,Republic of Sierra Leone,SL-RCHP2 Add'l Financing (FY13),Human development
16,8,Human development,52b213b38594d8a2be17c7b6,Republic of Sierra Leone,SL-RCHP2 Add'l Financing (FY13),Human development
17,8,Human development,52b213b38594d8a2be17c7c4,Lebanese Republic,LB: Mobile Internet Ecosystem Project (MIEP),Human development
18,8,Human development,52b213b38594d8a2be17c7c6,Republic of Tajikistan,Tajikistan Health Services Improvement Project...,Human development
19,8,Human development,52b213b38594d8a2be17c7c6,Republic of Tajikistan,Tajikistan Health Services Improvement Project...,Human development

In [315]:
#drop the original theme_name column and rename the new merged column 
df_theme_new.drop('theme_name_x', axis=1, inplace=True)
df_theme_new = df_theme_new.rename(columns = {'theme_name_y':'theme_name'})
df_theme_new.head(20)

,theme_code,project_id,countryname,project_name,theme_name
0,8,52b213b38594d8a2be17c780,Federal Democratic Republic of Ethiopia,Ethiopia General Education Quality Improvement...,Human development
1,8,52b213b38594d8a2be17c787,People's Republic of China,China Renewable Energy Scale-Up Program Phase II,Human development
2,8,52b213b38594d8a2be17c791,Republic of Madagascar,Emergency Support to Education For all Project,Human development
3,8,52b213b38594d8a2be17c792,Kingdom of Cambodia,Additional Financing for the Second Health Sec...,Human development
4,8,52b213b38594d8a2be17c792,Kingdom of Cambodia,Additional Financing for the Second Health Sec...,Human development
5,8,52b213b38594d8a2be17c792,Kingdom of Cambodia,Additional Financing for the Second Health Sec...,Human development
6,8,52b213b38594d8a2be17c797,Republic of Tajikistan,Tajikistan JSDF Nutrition Grant Scale Up,Human development
7,8,52b213b38594d8a2be17c797,Republic of Tajikistan,Tajikistan JSDF Nutrition Grant Scale Up,Human development
8,8,52b213b38594d8a2be17c79a,Lao People's Democratic Republic,Lao PDR Ninth Poverty Reduction Support Operation,Human development
9,8,52b213b38594d8a2be17c79e,People's Republic of Angola,Angola Learning for All Project,Human development
10,8,52b213b38594d8a2be17c7a2,People's Republic of Bangladesh,Additional Financing: Skills and Training Enha...,Human development
11,8,52b213b38594d8a2be17c7a9,Republic of Congo,Congo Skills Development for Employability Pro...,Human development
12,8,52b213b38594d8a2be17c7ab,Democratic Republic of Sao Tome and Prin,Sao Tome & Principe-Extractive Industries Tran...,Human development
13,8,52b213b38594d8a2be17c7ad,Africa,West Africa Regional Disease Surveillance Cap...,Human development
14,8,52b213b38594d8a2be17c7b6,Republic of Sierra Leone,SL-RCHP2 Add'l Financing (FY13),Human development
15,8,52b213b38594d8a2be17c7b6,Republic of Sierra Leone,SL-RCHP2 Add'l Financing (FY13),Human development
16,8,52b213b38594d8a2be17c7b6,Republic of Sierra Leone,SL-RCHP2 Add'l Financing (FY13),Human development
17,8,52b213b38594d8a2be17c7c4,Lebanese Republic,LB: Mobile Internet Ecosystem Project (MIEP),Human development
18,8,52b213b38594d8a2be17c7c6,Republic of Tajikistan,Tajikistan Health Services Improvement Project...,Human development
19,8,52b213b38594d8a2be17c7c6,Republic of Tajikistan,Tajikistan Health Services Improvement Project...,Human development

In [317]:
# get the top 10  project themes AFTER DATA CLEANSING

top10_proj_theme_new = df_theme_new.groupby(['theme_name'])['theme_name'] \
                            .count() \
                            .reset_index(name='count') \
                            .sort_values(['count'], ascending=False) \
                            .head(10) 

top10_proj_theme_new.reset_index(drop=True, inplace=True)
top10_proj_theme_new

                                     theme_name  count
0  Environment and natural resources management    250
1                             Rural development    216
2                             Human development    210
3                      Public sector governance    199
4         Social protection and risk management    168
5      Financial and private sector development    146
6                   Social dev/gender/inclusion    130
7                         Trade and integration     77
8                             Urban development     50
9                           Economic management     38

In [318]:
# Results BEFORE DATA CLEANSING

top10_proj_theme

                                     theme_name  count
0  Environment and natural resources management    223
1                             Rural development    202
2                             Human development    197
3                      Public sector governance    184
4         Social protection and risk management    158
5      Financial and private sector development    130
6                                                  122
7                   Social dev/gender/inclusion    119
8                         Trade and integration     72
9                             Urban development     47